name: Identity UX template
description: For writing identity UX tickets
labels: "Identity,Identity-UX"
projects:
  - department-of-veterans-affairs/1137
body:
- type: textarea
  attributes:
    label: Issue Description
    description: Describe the issue details
    placeholder: Insert issue details here
- type: markdown
  attributes:
    value: |
      ## Description of UX Tasks


      ### Documentation


      ### Product notes



      ### Acceptance Criteria
      - [ ] Documentation has been updated
      - [ ] Add finalized research to Github
      - [ ] Reviewed by UX Team
      - [ ] Reviewed by PMs



      ## How to configure this issue
      - [ ] **Attached to a Milestone** (when will this be completed?)
      - [ ] **Attached to an Epic** (what body of work is this a part of?)
      - [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
      - [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
      - [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
